### ISSUE TITLE
Doesnt work correctly for portrait window

### ISSUE THREAD

**Issue by Javigor** [anthonyec/godot_little_camera_preview#7]
Godot Version 4.2.1.stable.mono
I tried using the addon with a portrait game, and scalates the image when traying to.
It happens to me with any portrait value. The error starts when the viewport height value is greater than the viewport width value.
![image](https://github.com/anthonyec/godot_little_camera_preview/assets/93286256/a2dd2880-c35d-4289-8ebd-9488f1a244fd)
![image](https://github.com/anthonyec/godot_little_camera_preview/assets/93286256/f50a51fa-8968-4959-97f0-9adcd352e203)

**Comment by anthonyec** [comment]
Ooo nice catch! Yeah looks like the code just handles aspect ratio's greater than `1`,  I'll have a look into fixing this soon

**Comment by anthonyec** [comment]
@Javigor this has been fixed now, thanks for reporting!

I've updated the [release](https://github.com/anthonyec/godot_little_camera_preview/releases/tag/v1.2) on GitHub and it will available on the asset library soon. Let me know if you have any other issues.

**Comment by Javigor** [comment]
It works fine!
Thx!!
